#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn1
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="LapLichBaoVeLuanVan")]
	public partial class LinqDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCaTrongNgay(CaTrongNgay instance);
    partial void UpdateCaTrongNgay(CaTrongNgay instance);
    partial void DeleteCaTrongNgay(CaTrongNgay instance);
    partial void InsertDeTai(DeTai instance);
    partial void UpdateDeTai(DeTai instance);
    partial void DeleteDeTai(DeTai instance);
    partial void InsertGiangVien(GiangVien instance);
    partial void UpdateGiangVien(GiangVien instance);
    partial void DeleteGiangVien(GiangVien instance);
    partial void InsertLich(Lich instance);
    partial void UpdateLich(Lich instance);
    partial void DeleteLich(Lich instance);
    partial void InsertNhom(Nhom instance);
    partial void UpdateNhom(Nhom instance);
    partial void DeleteNhom(Nhom instance);
    partial void InsertPhanCong(PhanCong instance);
    partial void UpdatePhanCong(PhanCong instance);
    partial void DeletePhanCong(PhanCong instance);
    partial void InsertPhongHoc(PhongHoc instance);
    partial void UpdatePhongHoc(PhongHoc instance);
    partial void DeletePhongHoc(PhongHoc instance);
    #endregion
		
		public LinqDataContext() : 
				base(global::DoAn1.Properties.Settings.Default.LapLichBaoVeLuanVanConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public LinqDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CaTrongNgay> CaTrongNgays
		{
			get
			{
				return this.GetTable<CaTrongNgay>();
			}
		}
		
		public System.Data.Linq.Table<DeTai> DeTais
		{
			get
			{
				return this.GetTable<DeTai>();
			}
		}
		
		public System.Data.Linq.Table<GiangVien> GiangViens
		{
			get
			{
				return this.GetTable<GiangVien>();
			}
		}
		
		public System.Data.Linq.Table<Lich> Liches
		{
			get
			{
				return this.GetTable<Lich>();
			}
		}
		
		public System.Data.Linq.Table<Nhom> Nhoms
		{
			get
			{
				return this.GetTable<Nhom>();
			}
		}
		
		public System.Data.Linq.Table<PhanCong> PhanCongs
		{
			get
			{
				return this.GetTable<PhanCong>();
			}
		}
		
		public System.Data.Linq.Table<PhongHoc> PhongHocs
		{
			get
			{
				return this.GetTable<PhongHoc>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_getDanhSachPhanCongChuaTaoLich")]
		public ISingleResult<sp_getDanhSachPhanCongChuaTaoLichResult> sp_getDanhSachPhanCongChuaTaoLich()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_getDanhSachPhanCongChuaTaoLichResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_getDanhSachPhanCongChuaTaoLichTheoGiangVien")]
		public ISingleResult<sp_getDanhSachPhanCongChuaTaoLichTheoGiangVienResult> sp_getDanhSachPhanCongChuaTaoLichTheoGiangVien([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaGV", DbType="Int")] System.Nullable<int> maGV)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maGV);
			return ((ISingleResult<sp_getDanhSachPhanCongChuaTaoLichTheoGiangVienResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_getDeTaiChuaDuocPhanCong")]
		public ISingleResult<sp_getDeTaiChuaDuocPhanCongResult> sp_getDeTaiChuaDuocPhanCong([global::System.Data.Linq.Mapping.ParameterAttribute(Name="HocKy", DbType="Int")] System.Nullable<int> hocKy, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NamHoc", DbType="Int")] System.Nullable<int> namHoc)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), hocKy, namHoc);
			return ((ISingleResult<sp_getDeTaiChuaDuocPhanCongResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CaTrongNgay")]
	public partial class CaTrongNgay : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Ca;
		
		private string _ThoiDiem;
		
		private EntitySet<Lich> _Liches;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCaChanging(int value);
    partial void OnCaChanged();
    partial void OnThoiDiemChanging(string value);
    partial void OnThoiDiemChanged();
    #endregion
		
		public CaTrongNgay()
		{
			this._Liches = new EntitySet<Lich>(new Action<Lich>(this.attach_Liches), new Action<Lich>(this.detach_Liches));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ca", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Ca
		{
			get
			{
				return this._Ca;
			}
			set
			{
				if ((this._Ca != value))
				{
					this.OnCaChanging(value);
					this.SendPropertyChanging();
					this._Ca = value;
					this.SendPropertyChanged("Ca");
					this.OnCaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiDiem", DbType="Char(10)")]
		public string ThoiDiem
		{
			get
			{
				return this._ThoiDiem;
			}
			set
			{
				if ((this._ThoiDiem != value))
				{
					this.OnThoiDiemChanging(value);
					this.SendPropertyChanging();
					this._ThoiDiem = value;
					this.SendPropertyChanged("ThoiDiem");
					this.OnThoiDiemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CaTrongNgay_Lich", Storage="_Liches", ThisKey="Ca", OtherKey="Ca")]
		public EntitySet<Lich> Liches
		{
			get
			{
				return this._Liches;
			}
			set
			{
				this._Liches.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Liches(Lich entity)
		{
			this.SendPropertyChanging();
			entity.CaTrongNgay = this;
		}
		
		private void detach_Liches(Lich entity)
		{
			this.SendPropertyChanging();
			entity.CaTrongNgay = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DeTai")]
	public partial class DeTai : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TenDT;
		
		private int _NamHoc;
		
		private int _HocKy;
		
		private EntitySet<PhanCong> _PhanCongs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTenDTChanging(string value);
    partial void OnTenDTChanged();
    partial void OnNamHocChanging(int value);
    partial void OnNamHocChanged();
    partial void OnHocKyChanging(int value);
    partial void OnHocKyChanged();
    #endregion
		
		public DeTai()
		{
			this._PhanCongs = new EntitySet<PhanCong>(new Action<PhanCong>(this.attach_PhanCongs), new Action<PhanCong>(this.detach_PhanCongs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDT", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TenDT
		{
			get
			{
				return this._TenDT;
			}
			set
			{
				if ((this._TenDT != value))
				{
					this.OnTenDTChanging(value);
					this.SendPropertyChanging();
					this._TenDT = value;
					this.SendPropertyChanged("TenDT");
					this.OnTenDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamHoc", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int NamHoc
		{
			get
			{
				return this._NamHoc;
			}
			set
			{
				if ((this._NamHoc != value))
				{
					this.OnNamHocChanging(value);
					this.SendPropertyChanging();
					this._NamHoc = value;
					this.SendPropertyChanged("NamHoc");
					this.OnNamHocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HocKy", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int HocKy
		{
			get
			{
				return this._HocKy;
			}
			set
			{
				if ((this._HocKy != value))
				{
					this.OnHocKyChanging(value);
					this.SendPropertyChanging();
					this._HocKy = value;
					this.SendPropertyChanged("HocKy");
					this.OnHocKyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DeTai_PhanCong", Storage="_PhanCongs", ThisKey="TenDT,NamHoc,HocKy", OtherKey="TenDeTai,NamHoc,HocKy")]
		public EntitySet<PhanCong> PhanCongs
		{
			get
			{
				return this._PhanCongs;
			}
			set
			{
				this._PhanCongs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PhanCongs(PhanCong entity)
		{
			this.SendPropertyChanging();
			entity.DeTai = this;
		}
		
		private void detach_PhanCongs(PhanCong entity)
		{
			this.SendPropertyChanging();
			entity.DeTai = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GiangVien")]
	public partial class GiangVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaGV;
		
		private string _TenGV;
		
		private string _GioiTinh;
		
		private string _SDT;
		
		private string _ChucVu;
		
		private string _Email;
		
		private string _DiaChi;
		
		private System.Nullable<int> _SLDeTaiToiDa;
		
		private System.Nullable<int> _myIndex;
		
		private EntitySet<PhanCong> _PhanCongs;
		
		private EntitySet<PhanCong> _PhanCongs1;
		
		private EntitySet<PhanCong> _PhanCongs2;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaGVChanging(int value);
    partial void OnMaGVChanged();
    partial void OnTenGVChanging(string value);
    partial void OnTenGVChanged();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnChucVuChanging(string value);
    partial void OnChucVuChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnSLDeTaiToiDaChanging(System.Nullable<int> value);
    partial void OnSLDeTaiToiDaChanged();
    partial void OnmyIndexChanging(System.Nullable<int> value);
    partial void OnmyIndexChanged();
    #endregion
		
		public GiangVien()
		{
			this._PhanCongs = new EntitySet<PhanCong>(new Action<PhanCong>(this.attach_PhanCongs), new Action<PhanCong>(this.detach_PhanCongs));
			this._PhanCongs1 = new EntitySet<PhanCong>(new Action<PhanCong>(this.attach_PhanCongs1), new Action<PhanCong>(this.detach_PhanCongs1));
			this._PhanCongs2 = new EntitySet<PhanCong>(new Action<PhanCong>(this.attach_PhanCongs2), new Action<PhanCong>(this.detach_PhanCongs2));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaGV", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaGV
		{
			get
			{
				return this._MaGV;
			}
			set
			{
				if ((this._MaGV != value))
				{
					this.OnMaGVChanging(value);
					this.SendPropertyChanging();
					this._MaGV = value;
					this.SendPropertyChanged("MaGV");
					this.OnMaGVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenGV", DbType="NVarChar(50)")]
		public string TenGV
		{
			get
			{
				return this._TenGV;
			}
			set
			{
				if ((this._TenGV != value))
				{
					this.OnTenGVChanging(value);
					this.SendPropertyChanging();
					this._TenGV = value;
					this.SendPropertyChanged("TenGV");
					this.OnTenGVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(50)")]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="VarChar(50)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChucVu", DbType="NVarChar(50)")]
		public string ChucVu
		{
			get
			{
				return this._ChucVu;
			}
			set
			{
				if ((this._ChucVu != value))
				{
					this.OnChucVuChanging(value);
					this.SendPropertyChanging();
					this._ChucVu = value;
					this.SendPropertyChanged("ChucVu");
					this.OnChucVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(50)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SLDeTaiToiDa", DbType="Int")]
		public System.Nullable<int> SLDeTaiToiDa
		{
			get
			{
				return this._SLDeTaiToiDa;
			}
			set
			{
				if ((this._SLDeTaiToiDa != value))
				{
					this.OnSLDeTaiToiDaChanging(value);
					this.SendPropertyChanging();
					this._SLDeTaiToiDa = value;
					this.SendPropertyChanged("SLDeTaiToiDa");
					this.OnSLDeTaiToiDaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_myIndex", DbType="Int")]
		public System.Nullable<int> myIndex
		{
			get
			{
				return this._myIndex;
			}
			set
			{
				if ((this._myIndex != value))
				{
					this.OnmyIndexChanging(value);
					this.SendPropertyChanging();
					this._myIndex = value;
					this.SendPropertyChanged("myIndex");
					this.OnmyIndexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GiangVien_PhanCong", Storage="_PhanCongs", ThisKey="MaGV", OtherKey="GVHuongDan")]
		public EntitySet<PhanCong> PhanCongs
		{
			get
			{
				return this._PhanCongs;
			}
			set
			{
				this._PhanCongs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GiangVien_PhanCong1", Storage="_PhanCongs1", ThisKey="MaGV", OtherKey="GVPhanBien")]
		public EntitySet<PhanCong> PhanCongs1
		{
			get
			{
				return this._PhanCongs1;
			}
			set
			{
				this._PhanCongs1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GiangVien_PhanCong2", Storage="_PhanCongs2", ThisKey="MaGV", OtherKey="UyVien")]
		public EntitySet<PhanCong> PhanCongs2
		{
			get
			{
				return this._PhanCongs2;
			}
			set
			{
				this._PhanCongs2.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PhanCongs(PhanCong entity)
		{
			this.SendPropertyChanging();
			entity.GiangVien = this;
		}
		
		private void detach_PhanCongs(PhanCong entity)
		{
			this.SendPropertyChanging();
			entity.GiangVien = null;
		}
		
		private void attach_PhanCongs1(PhanCong entity)
		{
			this.SendPropertyChanging();
			entity.GiangVien1 = this;
		}
		
		private void detach_PhanCongs1(PhanCong entity)
		{
			this.SendPropertyChanging();
			entity.GiangVien1 = null;
		}
		
		private void attach_PhanCongs2(PhanCong entity)
		{
			this.SendPropertyChanging();
			entity.GiangVien2 = this;
		}
		
		private void detach_PhanCongs2(PhanCong entity)
		{
			this.SendPropertyChanging();
			entity.GiangVien2 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Lich")]
	public partial class Lich : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Ngay;
		
		private int _Ca;
		
		private int _Phong;
		
		private int _MaPC;
		
		private EntityRef<CaTrongNgay> _CaTrongNgay;
		
		private EntityRef<PhanCong> _PhanCong;
		
		private EntityRef<PhongHoc> _PhongHoc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNgayChanging(int value);
    partial void OnNgayChanged();
    partial void OnCaChanging(int value);
    partial void OnCaChanged();
    partial void OnPhongChanging(int value);
    partial void OnPhongChanged();
    partial void OnMaPCChanging(int value);
    partial void OnMaPCChanged();
    #endregion
		
		public Lich()
		{
			this._CaTrongNgay = default(EntityRef<CaTrongNgay>);
			this._PhanCong = default(EntityRef<PhanCong>);
			this._PhongHoc = default(EntityRef<PhongHoc>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngay", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Ngay
		{
			get
			{
				return this._Ngay;
			}
			set
			{
				if ((this._Ngay != value))
				{
					this.OnNgayChanging(value);
					this.SendPropertyChanging();
					this._Ngay = value;
					this.SendPropertyChanged("Ngay");
					this.OnNgayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ca", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Ca
		{
			get
			{
				return this._Ca;
			}
			set
			{
				if ((this._Ca != value))
				{
					if (this._CaTrongNgay.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCaChanging(value);
					this.SendPropertyChanging();
					this._Ca = value;
					this.SendPropertyChanged("Ca");
					this.OnCaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phong", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Phong
		{
			get
			{
				return this._Phong;
			}
			set
			{
				if ((this._Phong != value))
				{
					if (this._PhongHoc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPhongChanging(value);
					this.SendPropertyChanging();
					this._Phong = value;
					this.SendPropertyChanged("Phong");
					this.OnPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPC", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaPC
		{
			get
			{
				return this._MaPC;
			}
			set
			{
				if ((this._MaPC != value))
				{
					if (this._PhanCong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaPCChanging(value);
					this.SendPropertyChanging();
					this._MaPC = value;
					this.SendPropertyChanged("MaPC");
					this.OnMaPCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CaTrongNgay_Lich", Storage="_CaTrongNgay", ThisKey="Ca", OtherKey="Ca", IsForeignKey=true)]
		public CaTrongNgay CaTrongNgay
		{
			get
			{
				return this._CaTrongNgay.Entity;
			}
			set
			{
				CaTrongNgay previousValue = this._CaTrongNgay.Entity;
				if (((previousValue != value) 
							|| (this._CaTrongNgay.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CaTrongNgay.Entity = null;
						previousValue.Liches.Remove(this);
					}
					this._CaTrongNgay.Entity = value;
					if ((value != null))
					{
						value.Liches.Add(this);
						this._Ca = value.Ca;
					}
					else
					{
						this._Ca = default(int);
					}
					this.SendPropertyChanged("CaTrongNgay");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhanCong_Lich", Storage="_PhanCong", ThisKey="MaPC", OtherKey="MaPC", IsForeignKey=true)]
		public PhanCong PhanCong
		{
			get
			{
				return this._PhanCong.Entity;
			}
			set
			{
				PhanCong previousValue = this._PhanCong.Entity;
				if (((previousValue != value) 
							|| (this._PhanCong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PhanCong.Entity = null;
						previousValue.Liches.Remove(this);
					}
					this._PhanCong.Entity = value;
					if ((value != null))
					{
						value.Liches.Add(this);
						this._MaPC = value.MaPC;
					}
					else
					{
						this._MaPC = default(int);
					}
					this.SendPropertyChanged("PhanCong");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhongHoc_Lich", Storage="_PhongHoc", ThisKey="Phong", OtherKey="MaPH", IsForeignKey=true)]
		public PhongHoc PhongHoc
		{
			get
			{
				return this._PhongHoc.Entity;
			}
			set
			{
				PhongHoc previousValue = this._PhongHoc.Entity;
				if (((previousValue != value) 
							|| (this._PhongHoc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PhongHoc.Entity = null;
						previousValue.Liches.Remove(this);
					}
					this._PhongHoc.Entity = value;
					if ((value != null))
					{
						value.Liches.Add(this);
						this._Phong = value.MaPH;
					}
					else
					{
						this._Phong = default(int);
					}
					this.SendPropertyChanged("PhongHoc");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Nhom")]
	public partial class Nhom : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaNhom;
		
		private string _SV1;
		
		private string _SV2;
		
		private System.Nullable<int> _myIndex;
		
		private EntitySet<PhanCong> _PhanCongs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNhomChanging(int value);
    partial void OnMaNhomChanged();
    partial void OnSV1Changing(string value);
    partial void OnSV1Changed();
    partial void OnSV2Changing(string value);
    partial void OnSV2Changed();
    partial void OnmyIndexChanging(System.Nullable<int> value);
    partial void OnmyIndexChanged();
    #endregion
		
		public Nhom()
		{
			this._PhanCongs = new EntitySet<PhanCong>(new Action<PhanCong>(this.attach_PhanCongs), new Action<PhanCong>(this.detach_PhanCongs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhom", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaNhom
		{
			get
			{
				return this._MaNhom;
			}
			set
			{
				if ((this._MaNhom != value))
				{
					this.OnMaNhomChanging(value);
					this.SendPropertyChanging();
					this._MaNhom = value;
					this.SendPropertyChanged("MaNhom");
					this.OnMaNhomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SV1", DbType="NVarChar(50)")]
		public string SV1
		{
			get
			{
				return this._SV1;
			}
			set
			{
				if ((this._SV1 != value))
				{
					this.OnSV1Changing(value);
					this.SendPropertyChanging();
					this._SV1 = value;
					this.SendPropertyChanged("SV1");
					this.OnSV1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SV2", DbType="NVarChar(50)")]
		public string SV2
		{
			get
			{
				return this._SV2;
			}
			set
			{
				if ((this._SV2 != value))
				{
					this.OnSV2Changing(value);
					this.SendPropertyChanging();
					this._SV2 = value;
					this.SendPropertyChanged("SV2");
					this.OnSV2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_myIndex", DbType="Int")]
		public System.Nullable<int> myIndex
		{
			get
			{
				return this._myIndex;
			}
			set
			{
				if ((this._myIndex != value))
				{
					this.OnmyIndexChanging(value);
					this.SendPropertyChanging();
					this._myIndex = value;
					this.SendPropertyChanged("myIndex");
					this.OnmyIndexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Nhom_PhanCong", Storage="_PhanCongs", ThisKey="MaNhom", OtherKey="MaNhom")]
		public EntitySet<PhanCong> PhanCongs
		{
			get
			{
				return this._PhanCongs;
			}
			set
			{
				this._PhanCongs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PhanCongs(PhanCong entity)
		{
			this.SendPropertyChanging();
			entity.Nhom = this;
		}
		
		private void detach_PhanCongs(PhanCong entity)
		{
			this.SendPropertyChanging();
			entity.Nhom = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhanCong")]
	public partial class PhanCong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaPC;
		
		private System.Nullable<int> _GVHuongDan;
		
		private System.Nullable<int> _GVPhanBien;
		
		private System.Nullable<int> _UyVien;
		
		private System.Nullable<int> _MaNhom;
		
		private System.Nullable<int> _myIndex;
		
		private string _TenDeTai;
		
		private System.Nullable<int> _NamHoc;
		
		private System.Nullable<int> _HocKy;
		
		private EntitySet<Lich> _Liches;
		
		private EntityRef<DeTai> _DeTai;
		
		private EntityRef<GiangVien> _GiangVien;
		
		private EntityRef<GiangVien> _GiangVien1;
		
		private EntityRef<GiangVien> _GiangVien2;
		
		private EntityRef<Nhom> _Nhom;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPCChanging(int value);
    partial void OnMaPCChanged();
    partial void OnGVHuongDanChanging(System.Nullable<int> value);
    partial void OnGVHuongDanChanged();
    partial void OnGVPhanBienChanging(System.Nullable<int> value);
    partial void OnGVPhanBienChanged();
    partial void OnUyVienChanging(System.Nullable<int> value);
    partial void OnUyVienChanged();
    partial void OnMaNhomChanging(System.Nullable<int> value);
    partial void OnMaNhomChanged();
    partial void OnmyIndexChanging(System.Nullable<int> value);
    partial void OnmyIndexChanged();
    partial void OnTenDeTaiChanging(string value);
    partial void OnTenDeTaiChanged();
    partial void OnNamHocChanging(System.Nullable<int> value);
    partial void OnNamHocChanged();
    partial void OnHocKyChanging(System.Nullable<int> value);
    partial void OnHocKyChanged();
    #endregion
		
		public PhanCong()
		{
			this._Liches = new EntitySet<Lich>(new Action<Lich>(this.attach_Liches), new Action<Lich>(this.detach_Liches));
			this._DeTai = default(EntityRef<DeTai>);
			this._GiangVien = default(EntityRef<GiangVien>);
			this._GiangVien1 = default(EntityRef<GiangVien>);
			this._GiangVien2 = default(EntityRef<GiangVien>);
			this._Nhom = default(EntityRef<Nhom>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPC", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaPC
		{
			get
			{
				return this._MaPC;
			}
			set
			{
				if ((this._MaPC != value))
				{
					this.OnMaPCChanging(value);
					this.SendPropertyChanging();
					this._MaPC = value;
					this.SendPropertyChanged("MaPC");
					this.OnMaPCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GVHuongDan", DbType="Int")]
		public System.Nullable<int> GVHuongDan
		{
			get
			{
				return this._GVHuongDan;
			}
			set
			{
				if ((this._GVHuongDan != value))
				{
					if (this._GiangVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnGVHuongDanChanging(value);
					this.SendPropertyChanging();
					this._GVHuongDan = value;
					this.SendPropertyChanged("GVHuongDan");
					this.OnGVHuongDanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GVPhanBien", DbType="Int")]
		public System.Nullable<int> GVPhanBien
		{
			get
			{
				return this._GVPhanBien;
			}
			set
			{
				if ((this._GVPhanBien != value))
				{
					if (this._GiangVien1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnGVPhanBienChanging(value);
					this.SendPropertyChanging();
					this._GVPhanBien = value;
					this.SendPropertyChanged("GVPhanBien");
					this.OnGVPhanBienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UyVien", DbType="Int")]
		public System.Nullable<int> UyVien
		{
			get
			{
				return this._UyVien;
			}
			set
			{
				if ((this._UyVien != value))
				{
					if (this._GiangVien2.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUyVienChanging(value);
					this.SendPropertyChanging();
					this._UyVien = value;
					this.SendPropertyChanged("UyVien");
					this.OnUyVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhom", DbType="Int")]
		public System.Nullable<int> MaNhom
		{
			get
			{
				return this._MaNhom;
			}
			set
			{
				if ((this._MaNhom != value))
				{
					if (this._Nhom.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNhomChanging(value);
					this.SendPropertyChanging();
					this._MaNhom = value;
					this.SendPropertyChanged("MaNhom");
					this.OnMaNhomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_myIndex", DbType="Int")]
		public System.Nullable<int> myIndex
		{
			get
			{
				return this._myIndex;
			}
			set
			{
				if ((this._myIndex != value))
				{
					this.OnmyIndexChanging(value);
					this.SendPropertyChanging();
					this._myIndex = value;
					this.SendPropertyChanged("myIndex");
					this.OnmyIndexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDeTai", DbType="NVarChar(50)")]
		public string TenDeTai
		{
			get
			{
				return this._TenDeTai;
			}
			set
			{
				if ((this._TenDeTai != value))
				{
					if (this._DeTai.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTenDeTaiChanging(value);
					this.SendPropertyChanging();
					this._TenDeTai = value;
					this.SendPropertyChanged("TenDeTai");
					this.OnTenDeTaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamHoc", DbType="Int")]
		public System.Nullable<int> NamHoc
		{
			get
			{
				return this._NamHoc;
			}
			set
			{
				if ((this._NamHoc != value))
				{
					if (this._DeTai.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnNamHocChanging(value);
					this.SendPropertyChanging();
					this._NamHoc = value;
					this.SendPropertyChanged("NamHoc");
					this.OnNamHocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HocKy", DbType="Int")]
		public System.Nullable<int> HocKy
		{
			get
			{
				return this._HocKy;
			}
			set
			{
				if ((this._HocKy != value))
				{
					if (this._DeTai.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnHocKyChanging(value);
					this.SendPropertyChanging();
					this._HocKy = value;
					this.SendPropertyChanged("HocKy");
					this.OnHocKyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhanCong_Lich", Storage="_Liches", ThisKey="MaPC", OtherKey="MaPC")]
		public EntitySet<Lich> Liches
		{
			get
			{
				return this._Liches;
			}
			set
			{
				this._Liches.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DeTai_PhanCong", Storage="_DeTai", ThisKey="TenDeTai,NamHoc,HocKy", OtherKey="TenDT,NamHoc,HocKy", IsForeignKey=true)]
		public DeTai DeTai
		{
			get
			{
				return this._DeTai.Entity;
			}
			set
			{
				DeTai previousValue = this._DeTai.Entity;
				if (((previousValue != value) 
							|| (this._DeTai.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DeTai.Entity = null;
						previousValue.PhanCongs.Remove(this);
					}
					this._DeTai.Entity = value;
					if ((value != null))
					{
						value.PhanCongs.Add(this);
						this._TenDeTai = value.TenDT;
						this._NamHoc = value.NamHoc;
						this._HocKy = value.HocKy;
					}
					else
					{
						this._TenDeTai = default(string);
						this._NamHoc = default(Nullable<int>);
						this._HocKy = default(Nullable<int>);
					}
					this.SendPropertyChanged("DeTai");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GiangVien_PhanCong", Storage="_GiangVien", ThisKey="GVHuongDan", OtherKey="MaGV", IsForeignKey=true)]
		public GiangVien GiangVien
		{
			get
			{
				return this._GiangVien.Entity;
			}
			set
			{
				GiangVien previousValue = this._GiangVien.Entity;
				if (((previousValue != value) 
							|| (this._GiangVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._GiangVien.Entity = null;
						previousValue.PhanCongs.Remove(this);
					}
					this._GiangVien.Entity = value;
					if ((value != null))
					{
						value.PhanCongs.Add(this);
						this._GVHuongDan = value.MaGV;
					}
					else
					{
						this._GVHuongDan = default(Nullable<int>);
					}
					this.SendPropertyChanged("GiangVien");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GiangVien_PhanCong1", Storage="_GiangVien1", ThisKey="GVPhanBien", OtherKey="MaGV", IsForeignKey=true)]
		public GiangVien GiangVien1
		{
			get
			{
				return this._GiangVien1.Entity;
			}
			set
			{
				GiangVien previousValue = this._GiangVien1.Entity;
				if (((previousValue != value) 
							|| (this._GiangVien1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._GiangVien1.Entity = null;
						previousValue.PhanCongs1.Remove(this);
					}
					this._GiangVien1.Entity = value;
					if ((value != null))
					{
						value.PhanCongs1.Add(this);
						this._GVPhanBien = value.MaGV;
					}
					else
					{
						this._GVPhanBien = default(Nullable<int>);
					}
					this.SendPropertyChanged("GiangVien1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GiangVien_PhanCong2", Storage="_GiangVien2", ThisKey="UyVien", OtherKey="MaGV", IsForeignKey=true)]
		public GiangVien GiangVien2
		{
			get
			{
				return this._GiangVien2.Entity;
			}
			set
			{
				GiangVien previousValue = this._GiangVien2.Entity;
				if (((previousValue != value) 
							|| (this._GiangVien2.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._GiangVien2.Entity = null;
						previousValue.PhanCongs2.Remove(this);
					}
					this._GiangVien2.Entity = value;
					if ((value != null))
					{
						value.PhanCongs2.Add(this);
						this._UyVien = value.MaGV;
					}
					else
					{
						this._UyVien = default(Nullable<int>);
					}
					this.SendPropertyChanged("GiangVien2");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Nhom_PhanCong", Storage="_Nhom", ThisKey="MaNhom", OtherKey="MaNhom", IsForeignKey=true)]
		public Nhom Nhom
		{
			get
			{
				return this._Nhom.Entity;
			}
			set
			{
				Nhom previousValue = this._Nhom.Entity;
				if (((previousValue != value) 
							|| (this._Nhom.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Nhom.Entity = null;
						previousValue.PhanCongs.Remove(this);
					}
					this._Nhom.Entity = value;
					if ((value != null))
					{
						value.PhanCongs.Add(this);
						this._MaNhom = value.MaNhom;
					}
					else
					{
						this._MaNhom = default(Nullable<int>);
					}
					this.SendPropertyChanged("Nhom");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Liches(Lich entity)
		{
			this.SendPropertyChanging();
			entity.PhanCong = this;
		}
		
		private void detach_Liches(Lich entity)
		{
			this.SendPropertyChanging();
			entity.PhanCong = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhongHoc")]
	public partial class PhongHoc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaPH;
		
		private string _TenPH;
		
		private System.Nullable<int> _myIndex;
		
		private EntitySet<Lich> _Liches;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPHChanging(int value);
    partial void OnMaPHChanged();
    partial void OnTenPHChanging(string value);
    partial void OnTenPHChanged();
    partial void OnmyIndexChanging(System.Nullable<int> value);
    partial void OnmyIndexChanged();
    #endregion
		
		public PhongHoc()
		{
			this._Liches = new EntitySet<Lich>(new Action<Lich>(this.attach_Liches), new Action<Lich>(this.detach_Liches));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPH", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaPH
		{
			get
			{
				return this._MaPH;
			}
			set
			{
				if ((this._MaPH != value))
				{
					this.OnMaPHChanging(value);
					this.SendPropertyChanging();
					this._MaPH = value;
					this.SendPropertyChanged("MaPH");
					this.OnMaPHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenPH", DbType="NVarChar(50)")]
		public string TenPH
		{
			get
			{
				return this._TenPH;
			}
			set
			{
				if ((this._TenPH != value))
				{
					this.OnTenPHChanging(value);
					this.SendPropertyChanging();
					this._TenPH = value;
					this.SendPropertyChanged("TenPH");
					this.OnTenPHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_myIndex", DbType="Int")]
		public System.Nullable<int> myIndex
		{
			get
			{
				return this._myIndex;
			}
			set
			{
				if ((this._myIndex != value))
				{
					this.OnmyIndexChanging(value);
					this.SendPropertyChanging();
					this._myIndex = value;
					this.SendPropertyChanged("myIndex");
					this.OnmyIndexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhongHoc_Lich", Storage="_Liches", ThisKey="MaPH", OtherKey="Phong")]
		public EntitySet<Lich> Liches
		{
			get
			{
				return this._Liches;
			}
			set
			{
				this._Liches.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Liches(Lich entity)
		{
			this.SendPropertyChanging();
			entity.PhongHoc = this;
		}
		
		private void detach_Liches(Lich entity)
		{
			this.SendPropertyChanging();
			entity.PhongHoc = null;
		}
	}
	
	public partial class sp_getDanhSachPhanCongChuaTaoLichResult
	{
		
		private int _MaPC;
		
		private System.Nullable<int> _GVHuongDan;
		
		private System.Nullable<int> _GVPhanBien;
		
		private System.Nullable<int> _UyVien;
		
		private System.Nullable<int> _MaNhom;
		
		private System.Nullable<int> _myIndex;
		
		private string _TenDeTai;
		
		private System.Nullable<int> _NamHoc;
		
		private System.Nullable<int> _HocKy;
		
		public sp_getDanhSachPhanCongChuaTaoLichResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPC", DbType="Int NOT NULL")]
		public int MaPC
		{
			get
			{
				return this._MaPC;
			}
			set
			{
				if ((this._MaPC != value))
				{
					this._MaPC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GVHuongDan", DbType="Int")]
		public System.Nullable<int> GVHuongDan
		{
			get
			{
				return this._GVHuongDan;
			}
			set
			{
				if ((this._GVHuongDan != value))
				{
					this._GVHuongDan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GVPhanBien", DbType="Int")]
		public System.Nullable<int> GVPhanBien
		{
			get
			{
				return this._GVPhanBien;
			}
			set
			{
				if ((this._GVPhanBien != value))
				{
					this._GVPhanBien = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UyVien", DbType="Int")]
		public System.Nullable<int> UyVien
		{
			get
			{
				return this._UyVien;
			}
			set
			{
				if ((this._UyVien != value))
				{
					this._UyVien = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhom", DbType="Int")]
		public System.Nullable<int> MaNhom
		{
			get
			{
				return this._MaNhom;
			}
			set
			{
				if ((this._MaNhom != value))
				{
					this._MaNhom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_myIndex", DbType="Int")]
		public System.Nullable<int> myIndex
		{
			get
			{
				return this._myIndex;
			}
			set
			{
				if ((this._myIndex != value))
				{
					this._myIndex = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDeTai", DbType="NVarChar(50)")]
		public string TenDeTai
		{
			get
			{
				return this._TenDeTai;
			}
			set
			{
				if ((this._TenDeTai != value))
				{
					this._TenDeTai = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamHoc", DbType="Int")]
		public System.Nullable<int> NamHoc
		{
			get
			{
				return this._NamHoc;
			}
			set
			{
				if ((this._NamHoc != value))
				{
					this._NamHoc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HocKy", DbType="Int")]
		public System.Nullable<int> HocKy
		{
			get
			{
				return this._HocKy;
			}
			set
			{
				if ((this._HocKy != value))
				{
					this._HocKy = value;
				}
			}
		}
	}
	
	public partial class sp_getDanhSachPhanCongChuaTaoLichTheoGiangVienResult
	{
		
		private int _MaPC;
		
		private System.Nullable<int> _GVHuongDan;
		
		private System.Nullable<int> _GVPhanBien;
		
		private System.Nullable<int> _UyVien;
		
		private System.Nullable<int> _MaNhom;
		
		private System.Nullable<int> _myIndex;
		
		private string _TenDeTai;
		
		private System.Nullable<int> _NamHoc;
		
		private System.Nullable<int> _HocKy;
		
		public sp_getDanhSachPhanCongChuaTaoLichTheoGiangVienResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPC", DbType="Int NOT NULL")]
		public int MaPC
		{
			get
			{
				return this._MaPC;
			}
			set
			{
				if ((this._MaPC != value))
				{
					this._MaPC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GVHuongDan", DbType="Int")]
		public System.Nullable<int> GVHuongDan
		{
			get
			{
				return this._GVHuongDan;
			}
			set
			{
				if ((this._GVHuongDan != value))
				{
					this._GVHuongDan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GVPhanBien", DbType="Int")]
		public System.Nullable<int> GVPhanBien
		{
			get
			{
				return this._GVPhanBien;
			}
			set
			{
				if ((this._GVPhanBien != value))
				{
					this._GVPhanBien = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UyVien", DbType="Int")]
		public System.Nullable<int> UyVien
		{
			get
			{
				return this._UyVien;
			}
			set
			{
				if ((this._UyVien != value))
				{
					this._UyVien = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhom", DbType="Int")]
		public System.Nullable<int> MaNhom
		{
			get
			{
				return this._MaNhom;
			}
			set
			{
				if ((this._MaNhom != value))
				{
					this._MaNhom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_myIndex", DbType="Int")]
		public System.Nullable<int> myIndex
		{
			get
			{
				return this._myIndex;
			}
			set
			{
				if ((this._myIndex != value))
				{
					this._myIndex = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDeTai", DbType="NVarChar(50)")]
		public string TenDeTai
		{
			get
			{
				return this._TenDeTai;
			}
			set
			{
				if ((this._TenDeTai != value))
				{
					this._TenDeTai = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamHoc", DbType="Int")]
		public System.Nullable<int> NamHoc
		{
			get
			{
				return this._NamHoc;
			}
			set
			{
				if ((this._NamHoc != value))
				{
					this._NamHoc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HocKy", DbType="Int")]
		public System.Nullable<int> HocKy
		{
			get
			{
				return this._HocKy;
			}
			set
			{
				if ((this._HocKy != value))
				{
					this._HocKy = value;
				}
			}
		}
	}
	
	public partial class sp_getDeTaiChuaDuocPhanCongResult
	{
		
		private string _TenDT;
		
		private int _NamHoc;
		
		private int _HocKy;
		
		public sp_getDeTaiChuaDuocPhanCongResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDT", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenDT
		{
			get
			{
				return this._TenDT;
			}
			set
			{
				if ((this._TenDT != value))
				{
					this._TenDT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamHoc", DbType="Int NOT NULL")]
		public int NamHoc
		{
			get
			{
				return this._NamHoc;
			}
			set
			{
				if ((this._NamHoc != value))
				{
					this._NamHoc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HocKy", DbType="Int NOT NULL")]
		public int HocKy
		{
			get
			{
				return this._HocKy;
			}
			set
			{
				if ((this._HocKy != value))
				{
					this._HocKy = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
